### ISSUE TITLE
Would love an autosolve

### ISSUE THREAD

**Issue by tachijuan** [Canop/mazter#4]
Would be great to use this as a TUI screensaver if you could add an option for it to solve the maze. Similar to the widely used xscreensaver maze module (https://jwz.org/xscreensaver/screenshots/)

**Comment by Canop** [comment]
You mean an animation which loops creating maze and having the "player" automatically moved ?

This could be done, if we don't require the player to always win (unless we remove the monsters).

**Comment by tachijuan** [comment]
Correct. The player moved and the trace of the path being taken as part of the solution being highlighted. Simple depth first search or something like that showing the backtrack in a different color.

**Comment by Canop** [comment]
Searching isn't a problem. You may have missed it but when you lose, the shortest path to exit is shown.

**Comment by tachijuan** [comment]
I saw it and that's what gave me the idea!

**Comment by Canop** [comment]
This is really a fun idea. I think I'll do it as soon as I can find some time.

**Comment by Canop** [comment]
Made it : https://github.com/Canop/mazter/pull/5

Feedback welcome.

**Comment by Canop** [comment]
Version 2.0 released, with whole new levels

**Comment by tachijuan** [comment]
Love it. Thanks for doing this.
